version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 658761620615.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...          
      - docker build -t udacity-repos .
      - docker tag udacity-repos:$IMAGE_TAG 658761620615.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/udacity-repos     
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push udacity-repos.dkr.ecr.us-east-1.amazonaws.com/udacity-repos
